# Exact Duplicate Condition Audit

This notebook inspects the worst exact duplicate duplex groups and separates them into:
- same duplex + same conditions + conflicting labels
- same duplex + different conditions

The goal is to identify true candidate-removal groups versus biologically plausible repeats across changing conditions.

## Why This Audit Matters

- If the exact same duplex appears multiple times under the same conditions with very different inhibition values, that is a strong data-quality warning.
- If the same duplex appears under different concentrations, cell types, or times, then large label differences may be biologically real and should not be removed automatically.
- This notebook turns the previous duplicate warning signal into a cleaner action list.

In [1]:
%load_ext autoreload
%autoreload 2

import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from xgboost import XGBRegressor

project_root = Path.cwd().resolve()
while not (project_root / "utils").exists() and project_root != project_root.parent:
    project_root = project_root.parent

if not (project_root / "utils").exists():
    raise RuntimeError("Could not locate project root containing the utils package")

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from utils.merge_historic_data import load_merged_dataset
from utils.pipeline import SiRNADataPipeline
from utils.splitter import GroupKFoldLeakPerGroup

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)

## Step 1: Rebuild The Prediction Frame

Why: this keeps the duplicate audit aligned with the same cleaned dataset and held-out prediction frame used in the hotspot analysis notebooks.

In [2]:
cmsirna_path = os.environ.get("CMSIRNA_RAW_DATA_PATH")
historic_path = os.environ.get("CMSIRNA_RAW_HISTORIC_DATA_PATH")

assert cmsirna_path, "CMSIRNA_RAW_DATA_PATH is not set"
assert historic_path, "CMSIRNA_RAW_HISTORIC_DATA_PATH is not set"

raw_df = load_merged_dataset(cmsirna_path, historic_path)
pipeline = SiRNADataPipeline(target_len=25, fetch_missing_mrna=True)
enriched_df = pipeline.enrich_dataset_with_encodings(
    raw_df,
    strict_cleaning=True,
    add_mrna=True,
)
X, groups, y = pipeline.prepare_for_classical_ml(
    enriched_df,
    target_column="Inhibition",
    use_normalized_conditions=False,
)

mask = ~np.isnan(y)
X = X[mask]
groups = groups[mask]
y = y[mask]
analysis_df = enriched_df.loc[mask].reset_index(drop=True).copy()

analysis_df["patent_group"] = analysis_df.get(
    "patent_ID", pd.Series(index=analysis_df.index, dtype=object)
).fillna("HISTORIC_OR_UNKNOWN")

analysis_df.shape

loaded 3515 historic rows
merged 43153 CMsiRNA and 3515 historic rows into 46668
Running qc and data cleaning
dropped 4233 rows for in-vivo readings
dropped 565 rows for mM readings
dropped 115 rows for unknown or unwanted cell lines
dropped 47 rows for out-of-range inhibition
dropped 1749 rows for missing or unknown concentration
dropped 796 rows for concentration > 200 nM
filled 7522 rows for missing time of administration
dropped 2198 rows with a missing or >25 nt strand
dropped 6 columns: ['Modification_locations_Sense_strand', 'Modification_locations_Antisense_strand', 'Modifications_sense_strand', 'Modifications_AntiSense_strand_3_5', 'position_Antisense_strand', 'position_Sense_strand']
Mapping mRNA structural profiles
Error reading reference dataset: [Errno 2] No such file or directory: '/home/larsena8/software/fennec/src/fennec/support_files/train_data_v1.1.0_N=27742.csv'
Loaded 47 gene sequences from local cache
Loaded 0 gene sequences from reference CSV
Building gene -> mRNA mapping for 54 genes...
[1/54] Processing CTNNB1...
  Found in local cache (3074 bp)
[2/54] Processing INHBE...
  Found in local cache (2460 bp)
[3/54] Processing LPA...
  Found in local cache (6431 bp)
[4/54] Processing PNPLA3...
  Found in local cache (2753 bp)
[5/54] Processing APP...
  Found in local cache (3190 bp)
[6/54] Processing MAPT...
  Found in local cache (4139 bp)
[7/54] Processing MSTN...
  Found in local cache (2819 bp)
[8/54] Processing PLN...
  Found in local cache (2989 bp)
[9/54] Processing HSD17B13...
  Found in local cache (2260 bp)
[10/54] Processing MARC1...
  Found in local cache (7287 bp)
[11/54] Processing ANGPTL3...
  Found in local cache (2926 bp)
[12/54] Processing AGT...
  Found in local cache (2116 bp)
[13/54] Processing PCSK9...
  Found in local cache (3136 bp)
[14/54] Processing LAMIN A...
  Fetching LAMIN A from NCBI...
    No mRNA results found for LAMIN A
  WARNING: Could not resolve mRNA for LAMIN A
[15/54] Processing FIREFLY LUC...
  Fetching FIREFLY LUC from NCBI...
    No mRNA results found for FIREFLY LUC
  WARNING: Could not resolve mRNA for FIREFLY LUC
[16/54] Processing SEAP...
  Fetching SEAP from NCBI...
    No mRNA results found for SEAP
  WARNING: Could not resolve mRNA for SEAP
[17/54] Processing CYLOPHILIN B...
  Fetching CYLOPHILIN B from NCBI...
    No mRNA results found for CYLOPHILIN B
  WARNING: Could not resolve mRNA for CYLOPHILIN B
[18/54] Processing RENILLA LUC...
  Fetching RENILLA LUC from NCBI...
    No mRNA results found for RENILLA LUC
  WARNING: Could not resolve mRNA for RENILLA LUC
[19/54] Processing DBI...
  Found in local cache (564 bp)
[20/54] Processing PLK...
  Found in local cache (2160 bp)
[21/54] Processing GAPDH...
  Found in local cache (1231 bp)
[22/54] Processing MMAC1...
  Found in local cache (8514 bp)
[23/54] Processing ICAM-1...
  Fetching ICAM-1 from NCBI...
    No mRNA results found for ICAM-1
  WARNING: Could not resolve mRNA for ICAM-1
[24/54] Processing TC10...
  Found in local cache (4780 bp)
[25/54] Processing CDC34...
  Found in local cache (1418 bp)
[26/54] Processing UBE2D3...
  Found in local cache (3633 bp)
[27/54] Processing UBE2B...
  Found in local cache (2241 bp)
[28/54] Processing UBE2M...
  Found in local cache (1159 bp)
[29/54] Processing C6ORF110...
  Found in local cache (3245 bp)
[30/54] Processing RAB6IP1...
  Found in local cache (4919 bp)
[31/54] Processing UBE2L3...
  Found in local cache (2765 bp)
[32/54] Processing UBE2H...
  Found in local cache (4783 bp)
[33/54] Processing UBE2I...
  Found in local cache (2832 bp)
[34/54] Processing UBE2S...
  Found in local cache (2559 bp)
[35/54] Processing UBE2L6...
  Found in local cache (1218 bp)
[36/54] Processing UFC1...
  Found in local cache (888 bp)
[37/54] Processing HSPC150...
  Found in local cache (878 bp)
[38/54] Processing FLJ11011...
  Found in local cache (899 bp)
[39/54] Processing UBE2J1...
  Found in local cache (4164 bp)
[40/54] Processing HIP2...
  Found in local cache (4970 bp)
[41/54] Processing P2RX2...
  Found in local cache (1570 bp)
[42/54] Processing UBE2N...
  Found in local cache (4877 bp)
[43/54] Processing UBE2G1...
  Found in local cache (4167 bp)
[44/54] Processing UBE2E3...
  Found in local cache (1373 bp)
[45/54] Processing UBE2V1...
  Found in local cache (1049 bp)
[46/54] Processing FXYD6...
  Found in local cache (1678 bp)
[47/54] Processing TCAP...
  Found in local cache (960 bp)
[48/54] Processing CACNB1...
  Found in local cache (1720 bp)
[49/54] Processing MMP7...
  Found in local cache (1119 bp)
[50/54] Processing SOST...
  Found in local cache (2296 bp)
[51/54] Processing NOG...
  Found in local cache (1913 bp)
[52/54] Processing UBE2C...
  Found in local cache (572 bp)
[53/54] Processing P2RX3...
  Found in local cache (3792 bp)
[54/54] Processing EGFP...
  Fetching EGFP from NCBI...
    No mRNA results found for EGFP
  WARNING: Could not resolve mRNA for EGFP
Rows with mRNA: 36965/36965 (100.0%)
Removed 1521 rows. Remaining: 35444
edit_distance distribution:
edit_distance
0.0    16749
1.0    14603
2.0     2694
3.0      892
4.0      191
5.0      315
Name: count, dtype: int64
Dataset successfully enriched
Feature matrix X shape: (35444, 1425), target y shape: (35444,)

(35444, 40)

In [3]:
frozen_params = {
    "n_estimators": 800,
    "max_depth": 4,
    "learning_rate": 0.15881823130907038,
    "subsample": 0.8812898741586134,
    "colsample_bytree": 0.7824379872752019,
    "min_child_weight": 4,
    "reg_lambda": 0.8342807691178866,
    "reg_alpha": 1.4296995092035882,
    "gamma": 0.07531958697602548,
}

gene_cv = GroupKFoldLeakPerGroup(n_splits=3, leak_n=0, random_state=42)
oof_frames = []

for fold_id, (train_idx, test_idx) in enumerate(gene_cv.split(X, y, groups), start=1):
    model = XGBRegressor(tree_method="hist", n_jobs=-1, random_state=42, **frozen_params)
    model.fit(X[train_idx], y[train_idx])
    fold_pred = model.predict(X[test_idx])

    fold_frame = analysis_df.iloc[test_idx].reset_index().rename(columns={"index": "source_index"}).copy()
    fold_frame["row_index"] = test_idx
    fold_frame["fold_id"] = fold_id
    fold_frame["group"] = groups[test_idx]
    fold_frame["y_true"] = y[test_idx]
    fold_frame["y_pred"] = fold_pred
    fold_frame["abs_error"] = (fold_frame["y_true"] - fold_frame["y_pred"]).abs()
    oof_frames.append(fold_frame)

predictions_df = pd.concat(oof_frames, ignore_index=True)
predictions_df.head()

,source_index,ID,patent_ID,Authorization_status,Accession_number,gene_target_symbol_name,Gene_ID,The_name_of_double_helix,Antisense_seqence,length_anti_sense_strand,Modifications_AntiSense_strand,Modification_Types_Antisense_strand,Sense_seqence,length_sense_strand,Modification_Types_Sense_strand,Inhibition,SD,Cell_Type,Concentration,Time_of_administration,Title,mRNA,Concentration_nM,Time_of_administration_h,mRNA_five_prime,mRNA_three_prime,edit_distance,target_site_pct,Sense_Sequence_One_Hot,Antisense_Sequence_One_Hot,Sense_Acid_One_Hot,Sense_Sugar_One_Hot,Sense_Linker_One_Hot,Antisense_Acid_One_Hot,Antisense_Sugar_One_Hot,Antisense_Linker_One_Hot,Cell_Type_One_Hot,Concentration_log10_nM,Concentration_norm,Time_norm,patent_group,row_index,fold_id,group,y_true,y_pred,abs_error
0,4680,004-03-02-01275-1n-XXX--1.20,CN108368506A,Substantive Examination,NM_005577.4,LPA,4018.0,AD00571,TCGGCAGUCCCUUCUGCGUTT,21.0,dTCfgGfcAfgUfcCfcUfuCfuGfcGfudTsdT,1*2'-Deoxy thymidine || 2*2'-Fluorocytidine ||...,ACGCAGAAGGGACUGCCGAT,20.0,1*2'-Fluoroadenosine || 2*2'-O-Methylcytidine ...,-1.2,14.6,Hep3B,1.0,24.0,用于抑制LPA的基因表达的组合物和方法,GUAAGUCAACAAUGUCCUGGGAUUGGGACACACUUUCUGGGCACUG...,1.0,24.0,GUAAGUCAACAAUGUCCUGGGAUUGGGACACACUUUCUGGGCACUG...,UUGGACGGGAGACAGAGUGAAGCAUCAACCUACUUAGAAGCUGAAA...,2.0,0.058778,"[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0....","[[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], [0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",0.0,0.620954,0.121951,CN108368506A,4680,1,LPA,-1.2,34.769035,35.969035
1,4681,004-03-02-01276-1n-XXX-22.40,CN108368506A,Substantive Examination,NM_005577.4,LPA,4018.0,AD00572,TGUAGCACUCCUGCACCCCTT,21.0,dTGfuAfgCfaCfuCfcUfgCfaCfcCfcdTsdT,1*2'-Deoxy thymidine || 2*2'-Fluoroguanosine |...,GGGGUGCAGGAGUGCUACAT,20.0,1*2'-Fluoroguanosine || 2*2'-O-Methylguanosine...,22.4,6.2,Hep3B,1.0,24.0,用于抑制LPA的基因表达的组合物和方法,GUAAGUCAACAAUGUCCUGGGAUUGGGACACACUUUCUGGGCACUG...,1.0,24.0,GUAAGUCAACAAUGUCCUGGGAUUGGGACACACUUUCUGGGCACUG...,UUGGACGGGAGACAGAGUGAAGCAUCAACCUACUUAGAAGCUGAAA...,3.0,0.073084,"[[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0....","[[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], [0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",0.0,0.620954,0.121951,CN108368506A,4681,1,LPA,22.4,0.201030,22.198970
2,4682,004-03-02-01277-1n-XXX-29.20,CN108368506A,Substantive Examination,NM_005577.4,LPA,4018.0,AD00573,TAAUAAGGGGCUGCCACAGTT,21.0,dTAfaUfaAfgGfgGfcUfgCfcAfcAfgdTsdT,1*2'-Deoxy thymidine || 2*2'-Fluoroadenosine |...,CUGUGGCAGCCCCUUAUUAT,20.0,1*2'-Fluorocytidine || 2*2'-O-Methyluridine ||...,29.2,5.4,Hep3B,1.0,24.0,用于抑制LPA的基因表达的组合物和方法,GUAAGUCAACAAUGUCCUGGGAUUGGGACACACUUUCUGGGCACUG...,1.0,24.0,GUAAGUCAACAAUGUCCUGGGAUUGGGACACACUUUCUGGGCACUG...,UUGGACGGGAGACAGAGUGAAGCAUCAACCUACUUAGAAGCUGAAA...,3.0,0.419219,"[[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 1....","[[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], [1.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",0.0,0.620954,0.121951,CN108368506A,4682,1,LPA,29.2,47.724365,18.524365
3,4683,004-03-02-01278-1n-XXX-55.90,CN108368506A,Substantive Examination,NM_005577.4,LPA,4018.0,AD00574,TUAACAAUAAGGGGCUGCCTT,21.0,dTUfaAfcAfaUfaAfgGfgGfcUfgCfcdTsdT,1*2'-Deoxy thymidine || 2*2'-Fluorouridine || ...,GGCAGCCCCUUAUUGUUAAT,20.0,1*2'-Fluoroguanosine || 2*2'-O-Methylguanosine...,55.9,2.8,Hep3B,1.0,24.0,用于抑制LPA的基因表达的组合物和方法,GUAAGUCAACAAUGUCCUGGGAUUGGGACACACUUUCUGGGCACUG...,1.0,24.0,GUAAGUCAACAAUGUCCUGGGAUUGGGACACACUUUCUGGGCACUG...,UUGGACGGGAGACAGAGUGAAGCAUCAACCUACUUAGAAGCUGAAA...,3.0,0.419997,"[[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0....","[[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], [0.0, 1....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",0.0,0.620954,0.121951,CN108368506A,4683,1,LPA,55.9,45.757290,10.142710
4,4684,004-03-02-01279-1n-XXX-75.80,CN108368506A,Substantive Examination,NM_005577.4,LPA,4018.0,AD00575,TGUAUAACAAUAAGGGGCUTT,21.0,dTGfuAfuAfaCfaAfuAfaGfgGfgCfudTsdT,1*2'-Deoxy thymidine || 2*2'-Fluoroguanosine |...,AGCCCCUUAUUGUUAUACAT,20.0,1*2'-Fluoroadenosine || 2*2'-O-Methylguanosine...,75.8,3.8,Hep3B,1.0,24.0,用于抑制LPA的基因表达的组合物和方法,GUAAGUCAACAAUGUCCUGGGAUUGGGACACACUUUCUGGGCACUG...,1.0,24.0,GUAAGUCAACAAUGUCCUGGGAUUGGGACACACUUUCUGGGCACUG...,UUGGACGGGAGACAGAGUGAAGCAUCAACCUACUUAGAAGCUGAAA...,3.0,0.420463,"[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0....","[[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0], [0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]...","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0....","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",0.0,0.620954,0.121951,CN108368506A,4684,1,LPA,75.8,43.617760,32.182240

## Step 2: Build Exact Duplex Keys And Condition Keys

Why: we need one key for exact sequence identity and another key for whether the rows were measured under the same conditions.

In [4]:
def normalize_seq(value):
    if pd.isna(value):
        return None
    return "".join(str(value).upper().split())

predictions_df["sense_seq_norm"] = predictions_df["Sense_seqence"].map(normalize_seq)
predictions_df["antisense_seq_norm"] = predictions_df["Antisense_seqence"].map(normalize_seq)
predictions_df["duplex_key"] = (
    predictions_df["sense_seq_norm"].fillna("MISSING")
    + "||"
    + predictions_df["antisense_seq_norm"].fillna("MISSING")
)

condition_cols = [
    "group",
    "Cell_Type",
    "Concentration_nM",
    "Time_of_administration_h",
]

predictions_df["condition_key"] = predictions_df[condition_cols].astype(str).agg(" || ".join, axis=1)
predictions_df[["duplex_key", "condition_key"]].head()

                                    duplex_key                condition_key
0  ACGCAGAAGGGACUGCCGAT||TCGGCAGUCCCUUCUGCGUTT  LPA || Hep3B || 1.0 || 24.0
1  GGGGUGCAGGAGUGCUACAT||TGUAGCACUCCUGCACCCCTT  LPA || Hep3B || 1.0 || 24.0
2  CUGUGGCAGCCCCUUAUUAT||TAAUAAGGGGCUGCCACAGTT  LPA || Hep3B || 1.0 || 24.0
3  GGCAGCCCCUUAUUGUUAAT||TUAACAAUAAGGGGCUGCCTT  LPA || Hep3B || 1.0 || 24.0
4  AGCCCCUUAUUGUUAUACAT||TGUAUAACAAUAAGGGGCUTT  LPA || Hep3B || 1.0 || 24.0

## Step 3: Audit Exact Duplicate Groups

Why: we want to summarize each exact duplicate duplex group, then classify it as same-condition or different-condition.

In [5]:
rows = []
for duplex_key, dup_df in predictions_df.groupby("duplex_key"):
    if len(dup_df) < 2:
        continue

    unique_conditions = dup_df["condition_key"].nunique()
    rows.append({
        "duplex_key": duplex_key,
        "n_rows": len(dup_df),
        "n_condition_keys": unique_conditions,
        "same_condition_only": unique_conditions == 1,
        "group": dup_df["group"].mode().iloc[0],
        "cell_types": sorted(dup_df["Cell_Type"].astype(str).unique().tolist()),
        "concentrations": sorted(dup_df["Concentration_nM"].astype(float).unique().tolist()),
        "times": sorted(dup_df["Time_of_administration_h"].astype(float).unique().tolist()),
        "patents": sorted(dup_df["patent_group"].astype(str).unique().tolist()),
        "y_true_min": float(dup_df["y_true"].min()),
        "y_true_max": float(dup_df["y_true"].max()),
        "y_true_range": float(dup_df["y_true"].max() - dup_df["y_true"].min()),
        "mean_y_true": float(dup_df["y_true"].mean()),
        "row_indices": dup_df["row_index"].tolist(),
        "ids": dup_df.get("ID", pd.Series(index=dup_df.index, dtype=object)).astype(str).tolist(),
    })

duplicate_audit = pd.DataFrame(rows)
duplicate_audit.sort_values(["y_true_range", "n_rows"], ascending=[False, False]).head(30)

,duplex_key,n_rows,n_condition_keys,same_condition_only,group,cell_types,concentrations,times,patents,y_true_min,y_true_max,y_true_range,mean_y_true,row_indices,ids
6832,UUUUAUGUGCACACAUUAGGA||UCCUAAUGUGUGCACAUAAAACA,6,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-97.02,97.18,194.20,51.001667,"[16050, 16140, 16226, 16306, 16396, 16486]","[020-05-14-07142-10n-24h-71.82, 020-05-14-0714..."
6526,UUCCUGAUCACUAUGCAUUUA||UAAAUGCAUAGUGAUCAGGAAAG,12,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-91.48,99.68,191.16,64.055833,"[16013, 16056, 16101, 16146, 16191, 16232, 162...","[020-05-14-07104-10n-24h-87.15, 020-05-14-0714..."
4961,GUCUCACUUUCCAGCAAAA||UUUUGCUGGAAAGUGAGACCC,9,3,False,AGT,[Hep3B],"[0.01, 0.1, 1.0]",[24.0],[CN117448322A],-99.50,88.20,187.70,24.100000,"[29184, 29185, 29189, 29231, 29232, 29236, 292...","[078-12-02-13790-0.1n-24h-88.20, 078-12-02-137..."
4960,GUCUCACUUUCCAGCAAAAUU||UUUUGCUGGAAAGUGAGACCC,12,3,False,AGT,[Hep3B],"[0.01, 0.1, 1.0]",[24.0],[CN117448322A],-86.20,90.50,176.70,28.016667,"[29181, 29183, 29187, 29191, 29228, 29230, 292...","[078-12-02-13787-0.1n-24h-90.50, 078-12-02-137..."
4947,GUCGUUGGUGAAGUUUUUCAU||AUGAAAAACUUCACCAACGACUC,3,3,False,HSD17B13,"[COS7, Primary Cynomolgus Monkey Hepatocytes, ...",[50.0],[48.0],[CN112020556A],-95.00,80.60,175.60,13.000000,"[17822, 18076, 18330]","[032-09-09-08456-50n-48h-80.60, 032-09-03-0845..."
4502,GGAUGAUUGUACAGAAUCAUA||UAUGAUTCUGUACAAUCAUCCUG,6,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-80.61,90.96,171.57,42.060000,"[16086, 16176, 16254, 16342, 16432, 16522]","[020-05-14-07178-10n-24h-64.72, 020-05-14-0717..."
5492,UCAAACUAGUGCAUGAAUAGA||UCUAUUCAUGCACUAGUUUGAUA,11,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-74.04,97.28,171.32,39.504545,"[16027, 16070, 16115, 16160, 16205, 16281, 163...","[020-05-14-07118-10n-24h-71.30, 020-05-14-0716..."
5478,UAUUGAGAAUGAAGUGUGCAA||UUGCACACUUCAUUCUCAAUAAC,4,3,False,LPA,"[Huh7, RT-4]","[0.1, 1.0, 50.0]","[24.0, 48.0]",[CN116801886A],-91.64,78.57,170.21,31.347500,"[5651, 5742, 5830, 5891]","[009-03-05-03243-1n-XXX-78.57, 009-03-05-03243..."
6699,UUGUGCCUGUUUUAUGUGCAA||UUGCACAUAAAACAGGCACAAAG,12,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-69.52,98.48,168.00,61.400000,"[16034, 16077, 16122, 16167, 16212, 16248, 162...","[020-05-14-07125-10n-24h-72.77, 020-05-14-0716..."
4900,GUCCAAAGACGAAGUCGUGGU||ACCACGACUUCGUCUUUGGACCG,5,5,False,PNPLA3,"[Hep3B, HepG2]","[1.0, 10.0, 50.0]",[24.0],[WO2022256395A1],-86.36,80.80,167.16,-35.168000,"[11251, 11595, 11940, 12627, 12972]","[013-04-02-04394-50n-24h-80.80, 013-04-02-0439..."
1859,CACAAGAUUAUGGCCUGUA||UACAGGCCAUAAUCUUGUGUU,5,4,False,HSD17B13,[Primary human hepatocytes],"[0.1, 0.3, 1.0, 100.0]",[48.0],[WO2023091644A2],-67.64,84.74,152.38,6.478000,"[22256, 22357, 22412, 22559, 22706]","[039-09-03-09940-1n-48h-84.74, 039-09-03-09940..."
6551,UUCUACACUGUAUUACAUAAA||UUUAUGTAAUACAGUGUAGAAAG,10,8,False,APP,"[Be(2)C cell line, Neuro2A cell line, Primary ...","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-64.40,87.80,152.20,48.307000,"[14955, 15223, 15491, 15759, 16053, 16143, 162...","[020-05-04-06982-10n-24h-53.40, 020-05-04-0698..."
6455,UUAUGAAAAGCUAGGAAGCAA||UUGCTUCCUAGCUUUUCAUAAGG,7,7,False,PNPLA3,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes]","[0.1, 1.0, 10.0, 50.0, 100.0]",[24.0],[CN115176007A],-93.70,58.10,151.80,16.357143,"[9430, 9610, 9790, 9969, 10149, 10328, 10502]","[011-04-02-04126-50n-XXX-58.10, 011-04-02-0412..."
2136,CAGGUCAUGAGAGAAUGGGAA||UUCCCAUUCUCUCAUGACCUGGG,6,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-59.41,87.85,147.26,33.585000,"[16036, 16124, 16214, 16290, 16380, 16470]","[020-05-14-07127-10n-24h-39.65, 020-05-14-0712..."
5383,UAGGAUAAUGUCUUAUGUAAU||AUUACATAAGACAUUAUCCUAGU,70,7,False,PNPLA3,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes]","[0.1, 1.0, 10.0, 50.0, 100.0]",[24.0],[CN115176007A],-65.00,79.30,144.30,28.811429,"[9321, 9322, 9325, 9326, 9327, 9328, 9329, 933...","[011-04-02-04022-50n-XXX-67.00, 011-04-02-0402..."
4337,GCUUCACUACCCAUCGGUGUA||UACACCGAUGGGUAGUGAAGCAA,11,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-49.49,93.05,142.54,48.161818,"[16049, 16094, 16139, 16184, 16260, 16305, 163...","[020-05-14-07141-10n-24h-37.19, 020-05-14-0718..."
5180,GUUGUAUAUUAUUCUUGUGGA||UCCACAAGAAUAAUAUACAACUG,12,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-46.42,95.60,142.02,57.765000,"[16044, 16089, 16134, 16179, 16221, 16255, 163...","[020-05-14-07136-10n-24h-86.80, 020-05-14-0718..."
3865,GAUCAUAAUGGCAAUGUGGUU||AACCACAUUGCCAUUAUGAUCCA,15,11,False,INHBE,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes,...","[0.1, 1.0, 10.0, 100.0]",[24.0],[WO2023003922A1],-55.91,84.61,140.52,35.680667,"[1903, 2623, 3342, 3652, 3742, 3832, 3922, 401...","[003-02-02-01017-10n-24h-70.68, 003-02-02-0101..."
5179,GUUGGUUUUAUGAAAAGCUAU||AUAGCUUUUCAUAAAACCAACUC,22,11,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 1.0, 10.0, 50.0]",[24.0],[CN115176007A],-58.68,81.50,140.18,33.847273,"[6910, 7000, 7090, 7180, 7270, 7360, 7587, 772...","[011-04-09-03774-10n-24h-81.50, 011-04-09-0377..."
386,AAUACUGGGUUCACCAAAAAU||AUUUUUGGUGAACCCAGUAUUCA,7,7,False,HSD17B13,"[COS7, Primary Cynomolgus Monkey Hepatocytes, ...","[0.1, 10.0, 50.0]",[48.0],[CN112020556A],-86.10,53.80,139.90,-5.757143,"[17890, 18144, 18398, 18660, 19212, 19764, 20316]","[032-09-09-08562-50n-48h--8.10, 032-09-03-0856..."
1631,AUUCAGGUUCUUGGAAGAGAA||UUCUCUUCCAAGAACCUGAAUGC,8,8,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 10.0]",[24.0],[US20220117999A1],-90.93,48.70,139.63,7.347500,"[10679, 10750, 10820, 10891, 10962, 11033, 111...","[012-04-02-04303-10n-24h-48.70, 012-04-02-0430..."
3516,GAAGUCGUAAGAAGUCUGA||UCAGACUUCUUACGACUUCUU,5,4,False,HSD17B13,[Primary human hepatocytes],"[0.1, 0.3, 1.0, 100.0]",[48.0],[WO2023091644A2],-54.65,84.37,139.02,23.612000,"[22268, 22364, 22421, 22568, 22715]","[039-09-03-09952-1n-48h-84.37, 039-09-03-09952..."
3845,GAUAACCUUGACUACUAAAAU||AUUUTAGUAGUCAAGGUUAUCGU,42,7,False,PNPLA3,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes]","[0.1, 1.0, 10.0, 50.0, 100.0]",[24.0],[CN115176007A],-64.80,74.10,138.90,29.154762,"[9357, 9358, 9359, 9364, 9365, 9366, 9537, 953...","[011-04-02-04056-50n-XXX-72.30, 011-04-02-0405..."
447,AAUGUCCAGUGACAGAAUCAA||UUGAUUCUGUCACUGGACAUUGU,4,3,False,LPA,"[Huh7, RT-4]","[0.1, 1.0, 50.0]","[24.0, 48.0]",[CN116801886A],-45.73,93.02,138.75,52.377500,"[5688, 5779, 5864, 5899]","[009-03-05-03280-1n-XXX-93.02, 009-03-05-03280..."
5032,GUGCUAAAGUUUCCCAUCUUU||AAAGAUGGGAAACUUUAGCACCU,8,8,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 10.0]",[24.0],[US20220117999A1],-65.25,72.90,138.15,28.146250,"[10701, 10772, 10842, 10913, 10984, 11055, 111...","[012-04-02-04324-10n-24h-42.69, 012-04-02-0432..."
6318,UGUAUUGGAGACAGAUGAA||UUCAUCUGUCUCCAAUACAUU,5,4,False,HSD17B13,[Primary human hepatocytes],"[0.1, 0.3, 1.0, 100.0]",[48.0],[WO2023091644A2],-53.28,84.79,138.07,23.540000,"[22262, 22361, 22417, 22564, 22711]","[039-09-03-09946-1n-48h-84.79, 039-09-03-09946..."
2814,CGCGGCUGGAGCUUGUCCUUU||AAAGGACAAGCUCCAGCCGCGCU,6,6,False,PNPLA3,"[Hep3B, HepG2]","[1.0, 10.0, 50.0]",[24.0],[WO2022256395A1],-81.42,56.32,137.74,-3.625000,"[11220, 11565, 11909, 12254, 12596, 12941]","[013-04-02-04363-50n-24h-56.32, 013-04-02-0436..."
1133,AGGAAGCAACCUUUCGCCU||AGGCGAAAGGUUGCUUCCUGG,7,7,False,PNPLA3,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes]","[0.1, 1.0, 10.0, 50.0, 100.0]",[24.0],[CN115176007A],-71.30,65.90,137.20,19.814286,"[9445, 9625, 9805, 9984, 10164, 10343, 10517]","[011-04-02-04140-50n-XXX-65.90, 011-04-02-0414..."
1734,CAAAUGGGCACUUUCUUGUCU||AGACAAGAAAGTGCCCAUUUGGG,3,3,False,INHBE,[Hep3B],"[0.1, 1.0, 10.0]",[24.0],[WO2023003922A1],-52.32,84.77,137.09,11.813333,"[1994, 2714, 3433]","[003-02-02-01108-10n-24h-84.77, 003-02-02-0110..."
47,AAACCAUUGCUUCACUACCCA||UGGGUAGUGAAGCAAUGGUUUUG,17,9,False,APP,"[Be(2)C cell line, Hela, Neuro2A cell line, Pr...","[0.1, 1.0, 10.0, 20.0]",[24.0],"[US20220380773A1, WO2020132227A2]",-36.91,99.86,136.77,61.172941,"[14787, 15055, 15323, 15591, 16041, 16082, 161...","[020-05-04-06814-10n-24h-81.30, 020-05-04-0681..."

## Step 4: Split Into Same-Condition Conflicts And Different-Condition Repeats

Why: this is the actual decision boundary for cleanup. Same-condition conflicts are much stronger removal candidates than different-condition repeats.

In [6]:
same_condition_conflicts = duplicate_audit.loc[
    duplicate_audit["same_condition_only"]
].sort_values(["y_true_range", "n_rows"], ascending=[False, False]).reset_index(drop=True)

different_condition_duplicates = duplicate_audit.loc[
    ~duplicate_audit["same_condition_only"]
].sort_values(["y_true_range", "n_rows"], ascending=[False, False]).reset_index(drop=True)

print("Same duplex + same conditions + conflicting labels")
display(same_condition_conflicts.head(50))

print("Same duplex + different conditions")
display(different_condition_duplicates.head(50))

Same duplex + same conditions + conflicting labels

,duplex_key,n_rows,n_condition_keys,same_condition_only,group,cell_types,concentrations,times,patents,y_true_min,y_true_max,y_true_range,mean_y_true,row_indices,ids
0,GGCAACUUCCGGGACGAUGTT||CAUCGUCCCGGAAGUUGCC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-98.00,0.00,98.00,-49.000000,"[29589, 29590]","[080-13-11-14077-30n-XXX-0.00, 080-13-11-14078..."
1,UGUGCUAGUCGCUGCAAAACUUU||AAGUUUUGCAGCGACUAGCACA,5,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],7.00,87.00,80.00,55.200000,"[27986, 28034, 28036, 28038, 28043]","[070-12-11-13033-10n-XXX-12.00, 070-12-11-1307..."
2,GGGAUACCUCACCAAGAUCTT||GAUCUUGGUGAGGUAUCCC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-40.00,40.00,80.00,0.000000,"[29371, 29372]","[080-13-11-13889-30n-XXX-40.00, 080-13-11-1389..."
3,UUAUUCGGAAAAGCCAGCUTT||AGCUGGCUUUUCCGAAUAA,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-57.00,19.00,76.00,-19.000000,"[29555, 29556]","[080-13-11-14047-30n-XXX--57.00, 080-13-11-140..."
4,AUCGAGGGCAGGGUCAUGGTT||CCAUGACCCUGCCCUCGAU,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-60.00,8.00,68.00,-26.000000,"[29499, 29500]","[080-13-11-13999-30n-XXX--60.00, 080-13-11-140..."
5,UUUCUGGAUGGCAUCUAGCTT||GCUAGAUGCCAUCCAGAAA,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-23.00,44.00,67.00,10.500000,"[29819, 29820]","[080-13-11-14295-30n-XXX--23.00, 080-13-11-142..."
6,GAGGGUGUCUACGCCAUUGTT||CAAUGGCGUAGACACCCUC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],0.00,64.00,64.00,32.000000,"[29644, 29645]","[080-13-11-14135-30n-XXX-64.00, 080-13-11-1413..."
7,CCCAUGUCGACUACAUCGATT||UCGAUGUAGUCGACAUGGG,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-4.00,58.00,62.00,27.000000,"[29379, 29380]","[080-13-11-13895-30n-XXX-58.00, 080-13-11-1389..."
8,UCACCGUAUAUAUGGCAUGCAUU||AUGCAUGCCAUAUAUACGGUGA,5,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],22.00,83.00,61.00,50.200000,"[27955, 28006, 28014, 28022, 28031]","[070-12-11-13003-10n-XXX-22.00, 070-12-11-1304..."
9,UGUGGUCCUCCCACGCUCUCUAU||UAGAGAGCGUGGGAGGACCACA,4,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],22.00,83.00,61.00,48.000000,"[27983, 28009, 28017, 28025]","[070-12-11-13030-10n-XXX-83.00, 070-12-11-1304..."
10,UACGGGCUUCCGUAUAUAUGGAU||UCCAUAUAUACGGAAGCCCGUA,7,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],21.00,81.00,60.00,47.000000,"[27947, 27950, 27952, 27992, 27995, 27998, 28002]","[070-12-11-12999-10n-XXX-21.00, 070-12-11-1299..."
11,CAGGGUCAUGGUCACCGACTT||GUCGGUGACCAUGACCCUG,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-15.00,45.00,60.00,15.000000,"[29507, 29508]","[080-13-11-14006-30n-XXX-45.00, 080-13-11-1400..."
12,AGAGACUGAUCCACUUCUCTT||GAGAAGUGGAUCAGUCUCU,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-27.00,31.00,58.00,2.000000,"[29627, 29628]","[080-13-11-14109-30n-XXX-31.00, 080-13-11-1411..."
13,UGGUGGAGAGUCUCACUUUCCAU||UGGAAAGUGAGACUCUCCACCA,7,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],9.00,65.00,56.00,31.285714,"[27956, 27979, 27981, 28007, 28015, 28023, 28032]","[070-12-11-13004-10n-XXX-27.00, 070-12-11-1300..."
14,UCCAACUUCUCGGUGACUCAAGUU||ACUUGAGUCACCGAGAAGUUGGA,4,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],29.00,85.00,56.00,62.250000,"[27985, 28011, 28019, 28027]","[070-12-11-13032-10n-XXX-85.00, 070-12-11-1305..."
15,UGCUAGCCUUGCGUUCCGATT||UCGGAACGCAAGGCUAGCA,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],9.00,63.00,54.00,36.000000,"[29341, 29342]","[080-13-11-13863-30n-XXX-63.00, 080-13-11-1386..."
16,UGAGGCUGUGACAGGAUGGAAAU||UUUCCAUCCUGUCACAGCCUCA,5,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],33.00,81.00,48.00,60.200000,"[27951, 27994, 27997, 28000, 28003]","[070-12-11-13000-10n-XXX-66.00, 070-12-11-1303..."
17,UACGCUCUCUGGACUUCACAGAU||UCUGUGAAGUCCAGAGAGCGUA,4,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],18.00,65.00,47.00,43.250000,"[27953, 27993, 27996, 27999]","[070-12-11-13001-10n-XXX-29.00, 070-12-11-1303..."
18,CGCGUGCUCAACUGCCAAGTT||CUUGGCAGUUGAGCACGCG,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],3.00,49.00,46.00,26.000000,"[29524, 29525]","[080-13-11-14021-30n-XXX-49.00, 080-13-11-1402..."
19,UGCGCGUGCUCAACUGCCATT||UGGCAGUUGAGCACGCGCA,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],19.00,65.00,46.00,42.000000,"[29522, 29523]","[080-13-11-14019-30n-XXX-65.00, 080-13-11-1402..."
20,ACAGGCCAGCAAGUGUGACAGUCAU||AUGACUGUCACACUUGCUG,9,1,True,PCSK9,[Hela],[100.0],[48.0],[CN113980966A],49.00,94.00,45.00,80.222222,"[31365, 31374, 31383, 31390, 31391, 31395, 313...","[088-13-01-15353-100n-48h-93.00, 088-13-01-153..."
21,ACAGGCCAGCAAGUGUGACAGUCAU||AUGACGCACACUUGCUGGC...,11,1,True,PCSK9,[Hela],[100.0],[48.0],[CN113980966A],50.00,94.00,44.00,83.454545,"[31367, 31371, 31376, 31380, 31385, 31389, 313...","[088-13-01-15355-100n-48h-94.00, 088-13-01-153..."
22,CCAGCAUCCACGCUUCCUGTT||CAGGAAGCGUGGAUGCUGG,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],19.00,63.00,44.00,41.000000,"[29682, 29683]","[080-13-11-14165-30n-XXX-63.00, 080-13-11-1416..."
23,ACGGUACCGGGCGGAUGAATT||UUCAUCCGCCCGGUACCGU,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-45.00,-2.00,43.00,-23.500000,"[29390, 29391]","[080-13-11-13905-30n-XXX--45.00, 080-13-11-139..."
24,GGUACCGGGCGGAUGAAUATT||UAUUCAUCCGCCCGGUACC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],8.00,51.00,43.00,29.500000,"[29394, 29395]","[080-13-11-13909-30n-XXX-51.00, 080-13-11-1391..."
25,GUGACCACCGGGAAAUCGATT||UCGAUUUCCCGGUGGUCAC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],23.00,65.00,42.00,44.000000,"[29472, 29473]","[080-13-11-13975-30n-XXX-65.00, 080-13-11-1397..."
26,UUCCCGGCUGGAUGCGCACAAAU||UUUGUGCGCAUCCAGCCGGGAA,4,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],25.00,66.00,41.00,43.500000,"[27988, 28013, 28021, 28029]","[070-12-11-13035-10n-XXX-66.00, 070-12-11-1305..."
27,GCCAACCCGCUCCACUACCTT||GGUAGUGGAGCGGGUUGGC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],14.00,55.00,41.00,34.500000,"[29850, 29851]","[080-13-11-14325-30n-XXX-55.00, 080-13-11-1432..."
28,GGUCACCGCUGCCGGCAACTT||GUUGCCGGCAGCGGUGACC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-6.00,34.00,40.00,14.000000,"[29575, 29576]","[080-13-11-14065-30n-XXX-34.00, 080-13-11-1406..."
29,CAUAGGCCUGGAGUUUAUUTT||AAUAAACUCCAGGCCUAUG,6,1,True,PCSK9,[Hela],[30.0],[24.0],[CN101484588B],44.00,83.00,39.00,69.000000,"[29965, 29966, 29967, 29968, 29969, 29970]","[080-13-01-14430-30n-XXX-73.00, 080-13-01-1443..."
30,ACCACCGGGAAAUCGAGGGTT||CCCUCGAUUUCCCGGUGGU,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-22.00,17.00,39.00,-2.500000,"[29476, 29477]","[080-13-11-13979-30n-XXX--22.00, 080-13-11-139..."
31,CGGCAACUUCCGGGACGAUTT||AUCGUCCCGGAAGUUGCCG,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-22.00,17.00,39.00,-2.500000,"[29587, 29588]","[080-13-11-14075-30n-XXX-17.00, 080-13-11-1407..."
32,GAAGAUGAGUGGCGACCUGTT||CAGGUCGCCACUCAUCUUC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],24.00,63.00,39.00,43.500000,"[29377, 29378]","[080-13-11-13893-30n-XXX-63.00, 080-13-11-1389..."
33,UCCACCUCAUCAUCCACAAUGAU||UCAUUGUGGAUGAUGAGGUGGA,4,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],44.00,80.00,36.00,63.000000,"[27982, 28008, 28016, 28024]","[070-12-11-13029-10n-XXX-44.00, 070-12-11-1304..."
34,AGAGUGACCACCGGGAAAUTT||AUUUCCCGGUGGUCACUCU,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],19.00,55.00,36.00,37.000000,"[29467, 29468]","[080-13-11-13971-30n-XXX-55.00, 080-13-11-1397..."
35,UCUGGAUGUUGCUGCUGAGAAAU||UUUCUCAGCAGCAACAUCCAGA,4,1,True,AGT,[HepG2],[10.0],[24.0],[WO2023056446A1],55.00,89.00,34.00,76.750000,"[27984, 28010, 28018, 28026]","[070-12-11-13031-10n-XXX-55.00, 070-12-11-1304..."
36,AUCGAGGAGGACUCCUCUGTT||CAGAGGAGUCCUCCUCGAU,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-13.00,19.00,32.00,3.000000,"[29381, 29382]","[080-13-11-13897-30n-XXX--13.00, 080-13-11-138..."
37,CAGCGGCCGGGAUGCCGGCTT||GCCGGCAUCCCGGCCGCUG,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-26.00,6.00,32.00,-10.000000,"[29517, 29518]","[080-13-11-14014-30n-XXX--26.00, 080-13-11-140..."
38,GCAGAGACUGAUCCACUUCTT||GAAGUGGAUCAGUCUCUGC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],21.00,53.00,32.00,37.000000,"[29625, 29626]","[080-13-11-14107-30n-XXX-53.00, 080-13-11-1410..."
39,GUACCGGGCGGAUGAAUACTT||GUAUUCAUCCGCCCGGUAC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],11.00,43.00,32.00,27.000000,"[29396, 29397]","[080-13-11-13911-30n-XXX-43.00, 080-13-11-1391..."
40,CGGCACCCUCAUAGGCCUGTT||CAGGCCUAUGAGGGUGCCG,7,1,True,PCSK9,[Hela],[30.0],[24.0],[CN101484588B],15.00,46.00,31.00,33.000000,"[29492, 29493, 29494, 29495, 29496, 29497, 29498]","[080-13-01-13992-30n-XXX-15.00, 080-13-01-1399..."
41,GUGGUCAGCGGCCGGGAUGTT||CAUCCCGGCCGCUGACCAC,7,1,True,PCSK9,[Hela],[30.0],[24.0],[CN101484588B],3.00,33.00,30.00,20.000000,"[29670, 29671, 29672, 29673, 29674, 29675, 29676]","[080-13-01-14153-30n-XXX-14.00, 080-13-01-1415..."
42,UGGUUCCCUGAGGACCAGCTT||GCUGGUCCUCAGGGAACCA,7,1,True,PCSK9,[Hela],[30.0],[24.0],[CN101484588B],15.00,44.00,29.00,28.857143,"[29879, 29880, 29881, 29882, 29883, 29884, 29885]","[080-13-01-14352-30n-XXX-15.00, 080-13-01-1435..."
43,UGGCGGGUGGGUACAGCCGTT||CGGCUGUACCCACCCGCCA,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],9.00,38.00,29.00,23.500000,"[29561, 29562]","[080-13-11-14052-30n-XXX-9.00, 080-13-11-14053..."
44,CCUGCGCGUGCUCAACUGCTT||GCAGUUGAGCACGCGCAGG,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],-12.00,14.00,26.00,1.000000,"[29520, 29521]","[080-13-11-14017-30n-XXX--12.00, 080-13-11-140..."
45,UACUCUGCUCUAUGCCAGGTT||CCUGGCAUAGAGCAGAGUA,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],26.00,51.00,25.00,38.500000,"[29834, 29835]","[080-13-11-14310-30n-XXX-26.00, 080-13-11-1431..."
46,UAGCCUUGCGUUCCGAGGATT||UCCUCGGAACGCAAGGCUA,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],43.00,68.00,25.00,55.500000,"[29343, 29344]","[080-13-11-13865-30n-XXX-68.00, 080-13-11-1386..."
47,GUUGAGGCAGAGACUGAUCTT||GAUCAGUCUCUGCCUCAAC,2,1,True,PCSK9,[HepG2],[30.0],[24.0],[CN101484588B],24.00,48.00,24.00,36.000000,"[29623, 29624]","[080-13-11-14105-30n-XXX-24.00, 080-13-11-1410..."
48,AUGAAGAGAUUACCAAGACAUUU||AUGUCUUGGUAAUCUCUUCAUCC,2,1,True,HSD17B13,[Huh7],[0.1],[48.0],[CN116515835A],52.22,75.61,23.39,63.915000,"[20865, 20866]","[035-09-05-09484-0.1n-48h-75.61, 035-09-05-094..."
49,AGGCCUGGAGUUUAUUCGGTT||CCGAAUAAACUCCAGGCCU,7,1,True,PCSK9,[Hela],[30.0],[24.0],[CN101484588B],66.00,89.00,23.00,80.714286,"[29447, 29448, 29449, 29450, 29451, 29452, 29453]","[080-13-01-13954-30n-XXX-84.00, 080-13-01-1395..."

Same duplex + different conditions

,duplex_key,n_rows,n_condition_keys,same_condition_only,group,cell_types,concentrations,times,patents,y_true_min,y_true_max,y_true_range,mean_y_true,row_indices,ids
0,UUUUAUGUGCACACAUUAGGA||UCCUAAUGUGUGCACAUAAAACA,6,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-97.02,97.18,194.20,51.001667,"[16050, 16140, 16226, 16306, 16396, 16486]","[020-05-14-07142-10n-24h-71.82, 020-05-14-0714..."
1,UUCCUGAUCACUAUGCAUUUA||UAAAUGCAUAGUGAUCAGGAAAG,12,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-91.48,99.68,191.16,64.055833,"[16013, 16056, 16101, 16146, 16191, 16232, 162...","[020-05-14-07104-10n-24h-87.15, 020-05-14-0714..."
2,GUCUCACUUUCCAGCAAAA||UUUUGCUGGAAAGUGAGACCC,9,3,False,AGT,[Hep3B],"[0.01, 0.1, 1.0]",[24.0],[CN117448322A],-99.50,88.20,187.70,24.100000,"[29184, 29185, 29189, 29231, 29232, 29236, 292...","[078-12-02-13790-0.1n-24h-88.20, 078-12-02-137..."
3,GUCUCACUUUCCAGCAAAAUU||UUUUGCUGGAAAGUGAGACCC,12,3,False,AGT,[Hep3B],"[0.01, 0.1, 1.0]",[24.0],[CN117448322A],-86.20,90.50,176.70,28.016667,"[29181, 29183, 29187, 29191, 29228, 29230, 292...","[078-12-02-13787-0.1n-24h-90.50, 078-12-02-137..."
4,GUCGUUGGUGAAGUUUUUCAU||AUGAAAAACUUCACCAACGACUC,3,3,False,HSD17B13,"[COS7, Primary Cynomolgus Monkey Hepatocytes, ...",[50.0],[48.0],[CN112020556A],-95.00,80.60,175.60,13.000000,"[17822, 18076, 18330]","[032-09-09-08456-50n-48h-80.60, 032-09-03-0845..."
5,GGAUGAUUGUACAGAAUCAUA||UAUGAUTCUGUACAAUCAUCCUG,6,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-80.61,90.96,171.57,42.060000,"[16086, 16176, 16254, 16342, 16432, 16522]","[020-05-14-07178-10n-24h-64.72, 020-05-14-0717..."
6,UCAAACUAGUGCAUGAAUAGA||UCUAUUCAUGCACUAGUUUGAUA,11,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-74.04,97.28,171.32,39.504545,"[16027, 16070, 16115, 16160, 16205, 16281, 163...","[020-05-14-07118-10n-24h-71.30, 020-05-14-0716..."
7,UAUUGAGAAUGAAGUGUGCAA||UUGCACACUUCAUUCUCAAUAAC,4,3,False,LPA,"[Huh7, RT-4]","[0.1, 1.0, 50.0]","[24.0, 48.0]",[CN116801886A],-91.64,78.57,170.21,31.347500,"[5651, 5742, 5830, 5891]","[009-03-05-03243-1n-XXX-78.57, 009-03-05-03243..."
8,UUGUGCCUGUUUUAUGUGCAA||UUGCACAUAAAACAGGCACAAAG,12,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-69.52,98.48,168.00,61.400000,"[16034, 16077, 16122, 16167, 16212, 16248, 162...","[020-05-14-07125-10n-24h-72.77, 020-05-14-0716..."
9,GUCCAAAGACGAAGUCGUGGU||ACCACGACUUCGUCUUUGGACCG,5,5,False,PNPLA3,"[Hep3B, HepG2]","[1.0, 10.0, 50.0]",[24.0],[WO2022256395A1],-86.36,80.80,167.16,-35.168000,"[11251, 11595, 11940, 12627, 12972]","[013-04-02-04394-50n-24h-80.80, 013-04-02-0439..."
10,CACAAGAUUAUGGCCUGUA||UACAGGCCAUAAUCUUGUGUU,5,4,False,HSD17B13,[Primary human hepatocytes],"[0.1, 0.3, 1.0, 100.0]",[48.0],[WO2023091644A2],-67.64,84.74,152.38,6.478000,"[22256, 22357, 22412, 22559, 22706]","[039-09-03-09940-1n-48h-84.74, 039-09-03-09940..."
11,UUCUACACUGUAUUACAUAAA||UUUAUGTAAUACAGUGUAGAAAG,10,8,False,APP,"[Be(2)C cell line, Neuro2A cell line, Primary ...","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-64.40,87.80,152.20,48.307000,"[14955, 15223, 15491, 15759, 16053, 16143, 162...","[020-05-04-06982-10n-24h-53.40, 020-05-04-0698..."
12,UUAUGAAAAGCUAGGAAGCAA||UUGCTUCCUAGCUUUUCAUAAGG,7,7,False,PNPLA3,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes]","[0.1, 1.0, 10.0, 50.0, 100.0]",[24.0],[CN115176007A],-93.70,58.10,151.80,16.357143,"[9430, 9610, 9790, 9969, 10149, 10328, 10502]","[011-04-02-04126-50n-XXX-58.10, 011-04-02-0412..."
13,CAGGUCAUGAGAGAAUGGGAA||UUCCCAUUCUCUCAUGACCUGGG,6,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-59.41,87.85,147.26,33.585000,"[16036, 16124, 16214, 16290, 16380, 16470]","[020-05-14-07127-10n-24h-39.65, 020-05-14-0712..."
14,UAGGAUAAUGUCUUAUGUAAU||AUUACATAAGACAUUAUCCUAGU,70,7,False,PNPLA3,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes]","[0.1, 1.0, 10.0, 50.0, 100.0]",[24.0],[CN115176007A],-65.00,79.30,144.30,28.811429,"[9321, 9322, 9325, 9326, 9327, 9328, 9329, 933...","[011-04-02-04022-50n-XXX-67.00, 011-04-02-0402..."
15,GCUUCACUACCCAUCGGUGUA||UACACCGAUGGGUAGUGAAGCAA,11,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-49.49,93.05,142.54,48.161818,"[16049, 16094, 16139, 16184, 16260, 16305, 163...","[020-05-14-07141-10n-24h-37.19, 020-05-14-0718..."
16,GUUGUAUAUUAUUCUUGUGGA||UCCACAAGAAUAAUAUACAACUG,12,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-46.42,95.60,142.02,57.765000,"[16044, 16089, 16134, 16179, 16221, 16255, 163...","[020-05-14-07136-10n-24h-86.80, 020-05-14-0718..."
17,GAUCAUAAUGGCAAUGUGGUU||AACCACAUUGCCAUUAUGAUCCA,15,11,False,INHBE,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes,...","[0.1, 1.0, 10.0, 100.0]",[24.0],[WO2023003922A1],-55.91,84.61,140.52,35.680667,"[1903, 2623, 3342, 3652, 3742, 3832, 3922, 401...","[003-02-02-01017-10n-24h-70.68, 003-02-02-0101..."
18,GUUGGUUUUAUGAAAAGCUAU||AUAGCUUUUCAUAAAACCAACUC,22,11,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 1.0, 10.0, 50.0]",[24.0],[CN115176007A],-58.68,81.50,140.18,33.847273,"[6910, 7000, 7090, 7180, 7270, 7360, 7587, 772...","[011-04-09-03774-10n-24h-81.50, 011-04-09-0377..."
19,AAUACUGGGUUCACCAAAAAU||AUUUUUGGUGAACCCAGUAUUCA,7,7,False,HSD17B13,"[COS7, Primary Cynomolgus Monkey Hepatocytes, ...","[0.1, 10.0, 50.0]",[48.0],[CN112020556A],-86.10,53.80,139.90,-5.757143,"[17890, 18144, 18398, 18660, 19212, 19764, 20316]","[032-09-09-08562-50n-48h--8.10, 032-09-03-0856..."
20,AUUCAGGUUCUUGGAAGAGAA||UUCUCUUCCAAGAACCUGAAUGC,8,8,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 10.0]",[24.0],[US20220117999A1],-90.93,48.70,139.63,7.347500,"[10679, 10750, 10820, 10891, 10962, 11033, 111...","[012-04-02-04303-10n-24h-48.70, 012-04-02-0430..."
21,GAAGUCGUAAGAAGUCUGA||UCAGACUUCUUACGACUUCUU,5,4,False,HSD17B13,[Primary human hepatocytes],"[0.1, 0.3, 1.0, 100.0]",[48.0],[WO2023091644A2],-54.65,84.37,139.02,23.612000,"[22268, 22364, 22421, 22568, 22715]","[039-09-03-09952-1n-48h-84.37, 039-09-03-09952..."
22,GAUAACCUUGACUACUAAAAU||AUUUTAGUAGUCAAGGUUAUCGU,42,7,False,PNPLA3,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes]","[0.1, 1.0, 10.0, 50.0, 100.0]",[24.0],[CN115176007A],-64.80,74.10,138.90,29.154762,"[9357, 9358, 9359, 9364, 9365, 9366, 9537, 953...","[011-04-02-04056-50n-XXX-72.30, 011-04-02-0405..."
23,AAUGUCCAGUGACAGAAUCAA||UUGAUUCUGUCACUGGACAUUGU,4,3,False,LPA,"[Huh7, RT-4]","[0.1, 1.0, 50.0]","[24.0, 48.0]",[CN116801886A],-45.73,93.02,138.75,52.377500,"[5688, 5779, 5864, 5899]","[009-03-05-03280-1n-XXX-93.02, 009-03-05-03280..."
24,GUGCUAAAGUUUCCCAUCUUU||AAAGAUGGGAAACUUUAGCACCU,8,8,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 10.0]",[24.0],[US20220117999A1],-65.25,72.90,138.15,28.146250,"[10701, 10772, 10842, 10913, 10984, 11055, 111...","[012-04-02-04324-10n-24h-42.69, 012-04-02-0432..."
25,UGUAUUGGAGACAGAUGAA||UUCAUCUGUCUCCAAUACAUU,5,4,False,HSD17B13,[Primary human hepatocytes],"[0.1, 0.3, 1.0, 100.0]",[48.0],[WO2023091644A2],-53.28,84.79,138.07,23.540000,"[22262, 22361, 22417, 22564, 22711]","[039-09-03-09946-1n-48h-84.79, 039-09-03-09946..."
26,CGCGGCUGGAGCUUGUCCUUU||AAAGGACAAGCUCCAGCCGCGCU,6,6,False,PNPLA3,"[Hep3B, HepG2]","[1.0, 10.0, 50.0]",[24.0],[WO2022256395A1],-81.42,56.32,137.74,-3.625000,"[11220, 11565, 11909, 12254, 12596, 12941]","[013-04-02-04363-50n-24h-56.32, 013-04-02-0436..."
27,AGGAAGCAACCUUUCGCCU||AGGCGAAAGGUUGCUUCCUGG,7,7,False,PNPLA3,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes]","[0.1, 1.0, 10.0, 50.0, 100.0]",[24.0],[CN115176007A],-71.30,65.90,137.20,19.814286,"[9445, 9625, 9805, 9984, 10164, 10343, 10517]","[011-04-02-04140-50n-XXX-65.90, 011-04-02-0414..."
28,CAAAUGGGCACUUUCUUGUCU||AGACAAGAAAGTGCCCAUUUGGG,3,3,False,INHBE,[Hep3B],"[0.1, 1.0, 10.0]",[24.0],[WO2023003922A1],-52.32,84.77,137.09,11.813333,"[1994, 2714, 3433]","[003-02-02-01108-10n-24h-84.77, 003-02-02-0110..."
29,AAACCAUUGCUUCACUACCCA||UGGGUAGUGAAGCAAUGGUUUUG,17,9,False,APP,"[Be(2)C cell line, Hela, Neuro2A cell line, Pr...","[0.1, 1.0, 10.0, 20.0]",[24.0],"[US20220380773A1, WO2020132227A2]",-36.91,99.86,136.77,61.172941,"[14787, 15055, 15323, 15591, 16041, 16082, 161...","[020-05-04-06814-10n-24h-81.30, 020-05-04-0681..."
30,GUGCACACAUUAGGCAUUGAA||UUCAAUGCCUAAUGUGUGCACAU,12,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-40.07,95.40,135.47,46.340000,"[16047, 16092, 16137, 16182, 16224, 16258, 163...","[020-05-14-07139-10n-24h-62.55, 020-05-14-0718..."
31,UUUGUGCCUGUUUUAUGUGCA||UGCACATAAAACAGGCACAAAGA,6,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-47.89,86.97,134.86,38.765000,"[16076, 16166, 16247, 16332, 16422, 16512]","[020-05-14-07168-10n-24h-63.63, 020-05-14-0716..."
32,UAUGAAAAGCUAGGAAGCAAA||UUUGCUUCCUAGCUUUUCAUAAA,8,8,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 10.0]",[24.0],[US20220117999A1],-61.34,73.15,134.49,30.866250,"[10711, 10782, 10852, 10923, 10994, 11065, 111...","[012-04-02-04331-10n-24h-45.12, 012-04-02-0433..."
33,GUGUCUGAGUUCCAUUCCAAA||UUUGGAAUGGAACUCAGACACCA,6,6,False,PNPLA3,"[Hep3B, Primary Cynomolgus Monkey Hepatocytes,...","[0.1, 10.0]",[24.0],[US20220117999A1],-46.81,87.27,134.08,14.550000,"[10726, 10797, 10867, 10938, 11009, 11080]","[012-04-02-04343-10n-24h-8.71, 012-04-02-04343..."
34,AGAGGCUCCUUCCGAACAAGC||UUGUUCGGAAGGAGCCUCUAG,2,2,False,LPA,[Huh7],"[0.1, 10.0]",[24.0],[WO2022121959A1],-43.00,91.00,134.00,24.000000,"[5539, 5591]","[008-03-05-03177-0.1n-24h--43.00, 008-03-05-03..."
35,GCUGUAACACAAGUAGAUGCA||UGCAUCTACUUGUGUUACAGCAC,6,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-34.77,98.72,133.49,58.880000,"[16069, 16159, 16242, 16325, 16415, 16505]","[020-05-14-07161-10n-24h-68.26, 020-05-14-0716..."
36,UAUGUGAAUCAGUGAGAUGUU||AACAUCUCACUGAUUCACAUAAU,8,8,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 10.0]",[24.0],[US20220117999A1],-60.77,72.47,133.24,15.380000,"[10723, 10794, 10864, 10935, 11006, 11077, 111...","[012-04-02-04339-10n-24h-13.58, 012-04-02-0433..."
37,UUACCUGUUGAAUUUUGUAUU||AAUACAAAAUUCAACAGGUAACA,24,14,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 1.0, 10.0, 50.0]",[24.0],"[CN115176007A, US20220117999A1]",-51.26,81.05,132.31,43.103333,"[6251, 6368, 6485, 6602, 6652, 6680, 6708, 673...","[011-04-09-03584-50n-24h-80.70, 011-04-09-0358..."
38,UCACAGGAAGGACAUGUCAAU||AUUGACAUGUCCUUCCUGUGACA,4,3,False,LPA,"[Huh7, RT-4]","[0.1, 1.0, 50.0]","[24.0, 48.0]",[CN116801886A],-60.71,71.11,131.82,34.157500,"[5633, 5724, 5814, 5883]","[009-03-05-03225-1n-XXX-69.45, 009-03-05-03225..."
39,AAGAAGUCUGAUAGAUGGA||UCCAUCUAUCAGACUUCUUUU,4,3,False,HSD17B13,[Primary human hepatocytes],"[0.1, 0.3, 1.0]",[48.0],[WO2023091644A2],-50.25,81.36,131.61,22.165000,"[22271, 22422, 22569, 22716]","[039-09-03-09955-1n-48h-81.36, 039-09-03-09955..."
40,GUGCGAUAUGUGGAUGGAGGU||ACCUCCAUCCACAUAUCGCACGC,6,6,False,PNPLA3,"[Hep3B, HepG2]","[1.0, 10.0, 50.0]",[24.0],[WO2022256395A1],-57.84,73.73,131.57,-19.411667,"[11281, 11625, 11970, 12312, 12656, 13002]","[013-04-02-04424-50n-24h--30.29, 013-04-02-044..."
41,GGUUUUAUGAAAAGCUAGGAA||UUCCUAGCUUUUCAUAAAACCAA,16,12,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 1.0, 10.0, 50.0]",[24.0],"[CN115176007A, US20220117999A1]",-58.66,72.73,131.39,27.130625,"[8643, 8727, 8811, 8895, 8979, 9063, 9146, 923...","[011-04-02-03950-50n-24h-40.24, 011-04-02-0395..."
42,CUGGGCUUCUACCACGUCGGU||ACCGACGUGGUAGAAGCCCAGGA,6,6,False,PNPLA3,"[Hep3B, HepG2]","[1.0, 10.0, 50.0]",[24.0],[WO2022256395A1],-95.82,35.38,131.20,-14.840000,"[11228, 11573, 11917, 12262, 12604, 12949]","[013-04-02-04371-50n-24h--53.69, 013-04-02-043..."
43,AACCAUUGCUUCACUACCCAA||UUGGGUAGUGAAGCAAUGGUUUU,12,6,False,APP,"[Be(2)C cell line, Neuro2A cell line]","[0.1, 1.0, 10.0]",[24.0],[WO2020132227A2],-31.72,99.17,130.89,49.619167,"[16042, 16083, 16132, 16173, 16220, 16251, 162...","[020-05-14-07135-10n-24h-65.57, 020-05-14-0717..."
44,UUGGUUUUAUGAAAAGCUAGU||ACUAGCUUUUCAUAAAACCAACU,20,14,False,PNPLA3,"[COS7, Hep3B, HepG2, Primary Cynomolgus Monkey...","[0.1, 1.0, 10.0, 50.0]",[24.0],"[CN115176007A, WO2022256395A1]",-56.41,73.75,130.16,36.783000,"[6871, 6961, 7051, 7141, 7231, 7321, 8641, 872...","[011-04-09-03737-10n-24h-58.00, 011-04-09-0373..."
45,CCUCCUUCCUUCAGAGGCGUU||AACGCCTCUGAAGGAAGGAGGGA,5,5,False,PNPLA3,"[Hep3B, HepG2]","[1.0, 10.0, 50.0]",[24.0],[WO2022256395A1],-71.82,57.92,129.74,-23.598000,"[11270, 11614, 11959, 12301, 12991]","[013-04-02-04413-50n-24h--71.82, 013-04-02-044..."
46,GGCCAGGAGUCGGAACAUUGU||ACAATGTUCCGACUCCUGGCCUU,6,6,False,PNPLA3,"[Hep3B, HepG2]","[1.0, 10.0, 50.0]",[24.0],[WO2022256395A1],-96.89,32.57,129.46,-8.531667,"[11243, 11587, 11932, 12276, 12619, 12964]","[013-04-02-04386-50n-24h-1.76, 013-04-02-04386..."
47,AAUCCAAGCACAAGAUUAU||AUAAUCUUGUGCUUGGAUUUU,22,21,False,HSD17B13,"[HEK293A, Huh7, Primary human hepatocytes]","[0.0003, 0.001, 0.003, 0.009, 0.01, 0.027, 0.0...",[24.0],[CN116940681A],-32.40,95.60,128.00,61.609091,"[21192, 21211, 21227, 21243, 21259, 21275, 212...","[036-09-05-09575-10n-24h-86.10, 036-09-07-0957..."
48,GGGUUCACCAAAAAUCCAA||UUGGAUUUUUGGUGAACCCUU,5,4,False,HSD17B13,[Primary human hepatocytes],"[0.1, 0.3, 1.0, 100.0]",[48.0],[WO2023091644A2],-35.57,92.29,127.86,37.284000,"[22253, 22356, 22411, 22558, 22705]","[039-09-03-09937-1n-48h-82.90, 039-09-03-09937..."
49,AUACAUGAGCAAGAUUUGCAA||UUGCAAAUCUUGCUCAUGUAUCC,8,8,False,PNPLA3,"[COS7, Hep3B, Primary Cynomolgus Monkey Hepato...","[0.1, 10.0]",[24.0],[US20220117999A1],-52.46,75.26,127.72,32.123750,"[10686, 10757, 10827, 10898, 10969, 11040, 111...","[012-04-02-04310-10n-24h-62.70, 012-04-02-0431..."

## Step 5: Build A Conservative Candidate-Removal Table

Why: a practical first pass is to flag only same-condition duplicates with very large label ranges.

In [7]:
RANGE_THRESHOLD = 40.0

candidate_removal_table = same_condition_conflicts.loc[
    same_condition_conflicts["y_true_range"] >= RANGE_THRESHOLD
].copy()

candidate_removal_table[[
    "duplex_key",
    "group",
    "n_rows",
    "y_true_min",
    "y_true_max",
    "y_true_range",
    "cell_types",
    "concentrations",
    "times",
    "patents",
]].head(100)

,duplex_key,group,n_rows,y_true_min,y_true_max,y_true_range,cell_types,concentrations,times,patents
0,GGCAACUUCCGGGACGAUGTT||CAUCGUCCCGGAAGUUGCC,PCSK9,2,-98.0,0.0,98.0,[HepG2],[30.0],[24.0],[CN101484588B]
1,UGUGCUAGUCGCUGCAAAACUUU||AAGUUUUGCAGCGACUAGCACA,AGT,5,7.0,87.0,80.0,[HepG2],[10.0],[24.0],[WO2023056446A1]
2,GGGAUACCUCACCAAGAUCTT||GAUCUUGGUGAGGUAUCCC,PCSK9,2,-40.0,40.0,80.0,[HepG2],[30.0],[24.0],[CN101484588B]
3,UUAUUCGGAAAAGCCAGCUTT||AGCUGGCUUUUCCGAAUAA,PCSK9,2,-57.0,19.0,76.0,[HepG2],[30.0],[24.0],[CN101484588B]
4,AUCGAGGGCAGGGUCAUGGTT||CCAUGACCCUGCCCUCGAU,PCSK9,2,-60.0,8.0,68.0,[HepG2],[30.0],[24.0],[CN101484588B]
5,UUUCUGGAUGGCAUCUAGCTT||GCUAGAUGCCAUCCAGAAA,PCSK9,2,-23.0,44.0,67.0,[HepG2],[30.0],[24.0],[CN101484588B]
6,GAGGGUGUCUACGCCAUUGTT||CAAUGGCGUAGACACCCUC,PCSK9,2,0.0,64.0,64.0,[HepG2],[30.0],[24.0],[CN101484588B]
7,CCCAUGUCGACUACAUCGATT||UCGAUGUAGUCGACAUGGG,PCSK9,2,-4.0,58.0,62.0,[HepG2],[30.0],[24.0],[CN101484588B]
8,UCACCGUAUAUAUGGCAUGCAUU||AUGCAUGCCAUAUAUACGGUGA,AGT,5,22.0,83.0,61.0,[HepG2],[10.0],[24.0],[WO2023056446A1]
9,UGUGGUCCUCCCACGCUCUCUAU||UAGAGAGCGUGGGAGGACCACA,AGT,4,22.0,83.0,61.0,[HepG2],[10.0],[24.0],[WO2023056446A1]
10,UACGGGCUUCCGUAUAUAUGGAU||UCCAUAUAUACGGAAGCCCGUA,AGT,7,21.0,81.0,60.0,[HepG2],[10.0],[24.0],[WO2023056446A1]
11,CAGGGUCAUGGUCACCGACTT||GUCGGUGACCAUGACCCUG,PCSK9,2,-15.0,45.0,60.0,[HepG2],[30.0],[24.0],[CN101484588B]
12,AGAGACUGAUCCACUUCUCTT||GAGAAGUGGAUCAGUCUCU,PCSK9,2,-27.0,31.0,58.0,[HepG2],[30.0],[24.0],[CN101484588B]
13,UGGUGGAGAGUCUCACUUUCCAU||UGGAAAGUGAGACUCUCCACCA,AGT,7,9.0,65.0,56.0,[HepG2],[10.0],[24.0],[WO2023056446A1]
14,UCCAACUUCUCGGUGACUCAAGUU||ACUUGAGUCACCGAGAAGUUGGA,AGT,4,29.0,85.0,56.0,[HepG2],[10.0],[24.0],[WO2023056446A1]
15,UGCUAGCCUUGCGUUCCGATT||UCGGAACGCAAGGCUAGCA,PCSK9,2,9.0,63.0,54.0,[HepG2],[30.0],[24.0],[CN101484588B]
16,UGAGGCUGUGACAGGAUGGAAAU||UUUCCAUCCUGUCACAGCCUCA,AGT,5,33.0,81.0,48.0,[HepG2],[10.0],[24.0],[WO2023056446A1]
17,UACGCUCUCUGGACUUCACAGAU||UCUGUGAAGUCCAGAGAGCGUA,AGT,4,18.0,65.0,47.0,[HepG2],[10.0],[24.0],[WO2023056446A1]
18,CGCGUGCUCAACUGCCAAGTT||CUUGGCAGUUGAGCACGCG,PCSK9,2,3.0,49.0,46.0,[HepG2],[30.0],[24.0],[CN101484588B]
19,UGCGCGUGCUCAACUGCCATT||UGGCAGUUGAGCACGCGCA,PCSK9,2,19.0,65.0,46.0,[HepG2],[30.0],[24.0],[CN101484588B]
20,ACAGGCCAGCAAGUGUGACAGUCAU||AUGACUGUCACACUUGCUG,PCSK9,9,49.0,94.0,45.0,[Hela],[100.0],[48.0],[CN113980966A]
21,ACAGGCCAGCAAGUGUGACAGUCAU||AUGACGCACACUUGCUGGC...,PCSK9,11,50.0,94.0,44.0,[Hela],[100.0],[48.0],[CN113980966A]
22,CCAGCAUCCACGCUUCCUGTT||CAGGAAGCGUGGAUGCUGG,PCSK9,2,19.0,63.0,44.0,[HepG2],[30.0],[24.0],[CN101484588B]
23,ACGGUACCGGGCGGAUGAATT||UUCAUCCGCCCGGUACCGU,PCSK9,2,-45.0,-2.0,43.0,[HepG2],[30.0],[24.0],[CN101484588B]
24,GGUACCGGGCGGAUGAAUATT||UAUUCAUCCGCCCGGUACC,PCSK9,2,8.0,51.0,43.0,[HepG2],[30.0],[24.0],[CN101484588B]
25,GUGACCACCGGGAAAUCGATT||UCGAUUUCCCGGUGGUCAC,PCSK9,2,23.0,65.0,42.0,[HepG2],[30.0],[24.0],[CN101484588B]
26,UUCCCGGCUGGAUGCGCACAAAU||UUUGUGCGCAUCCAGCCGGGAA,AGT,4,25.0,66.0,41.0,[HepG2],[10.0],[24.0],[WO2023056446A1]
27,GCCAACCCGCUCCACUACCTT||GGUAGUGGAGCGGGUUGGC,PCSK9,2,14.0,55.0,41.0,[HepG2],[30.0],[24.0],[CN101484588B]
28,GGUCACCGCUGCCGGCAACTT||GUUGCCGGCAGCGGUGACC,PCSK9,2,-6.0,34.0,40.0,[HepG2],[30.0],[24.0],[CN101484588B]

## Step 6: Inspect One Duplicate Group In Detail

Why: before removing anything, it helps to inspect a few of the worst groups row by row.

In [8]:
if candidate_removal_table.empty:
    print("No candidate removal groups found at the current threshold.")
else:
    chosen_duplex = candidate_removal_table.iloc[0]["duplex_key"]
    print("Inspecting duplex:", chosen_duplex)
    display(
        predictions_df.loc[predictions_df["duplex_key"] == chosen_duplex, [
            "ID",
            "group",
            "Cell_Type",
            "Concentration_nM",
            "Time_of_administration_h",
            "patent_group",
            "y_true",
            "y_pred",
            "abs_error",
            "sense_seq_norm",
            "antisense_seq_norm",
        ]].sort_values("y_true")
    )

Inspecting duplex: GGCAACUUCCGGGACGAUGTT||CAUCGUCCCGGAAGUUGCC

,ID,group,Cell_Type,Concentration_nM,Time_of_administration_h,patent_group,y_true,y_pred,abs_error,sense_seq_norm,antisense_seq_norm
20436,080-13-11-14078-30n-XXX--98.00,PCSK9,HepG2,30.0,24.0,CN101484588B,-98.0,20.089787,118.089787,GGCAACUUCCGGGACGAUGTT,CAUCGUCCCGGAAGUUGCC
20435,080-13-11-14077-30n-XXX-0.00,PCSK9,HepG2,30.0,24.0,CN101484588B,0.0,60.210617,60.210617,GGCAACUUCCGGGACGAUGTT,CAUCGUCCCGGAAGUUGCC

## How To Use The Results

- `same_condition_conflicts` is the main cleanup table.
- `different_condition_duplicates` should usually be kept unless there is another quality problem.
- `candidate_removal_table` is a conservative shortlist for targeted cleaning.
- After review, use this shortlist for a cleaned-data ablation rather than deleting broad patents or whole genes.