In [1]:
%load_ext autoreload
%autoreload 2

from chemistry_encoding import ChemistryEncoder
from sequence_encoding import SequenceEncoder
from data_cleaning import DataCleaner
from experimental_encoding import ExperimentalEncoder, FeatureNormalizer

import pandas as pd

In [2]:
path = r"/Users/mac/Library/Mobile Documents/com~apple~CloudDocs/Master/MLRG/p14-crew/dataset/primary_dataset/CMsiRNA_data_update.tsv"
df_raw = pd.read_csv(path, sep="\t", low_memory=False)

cleaner = DataCleaner(df_raw.copy())
df_clean = cleaner.clean()  # row cleaning only; column dropping disabled in data_cleaning.py

print(f"Rows: {len(df_raw):,} → {len(df_clean):,} (dropped {len(df_raw) - len(df_clean):,})")
df_clean.head()

dropped 5756 rows (in-vivo 4233, mM 565, conc>200 797, cell 115, inhibition 102)
dropped 2937 rows with a missing or >25 nt strand
dropped 4 columns: ['Modification_locations_Sense_strand', 'Modification_locations_Antisense_strand', 'Modifications_sense_strand', 'position_Sense_strand']
Rows: 43,153 → 34,460 (dropped 8,693)

,ID,patent_ID,Authorization_status,Accession_number,Target_Gene,Gene_ID,The_name_of_double_helix,Antisense_seqence,length_anti_sense_strand,Modifications_AntiSense_strand,...,position_Sense_strand,Inhibition,SD,Cell_Type,Concentration,Time_of_administration,Title,Modifications_AntiSense_strand_3_5,Concentration_nM,Time_of_administration_h
0,001-01-01-00001-100n-48h-88.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D1,UUAGAAAGCUGAUGGACCAUAACUG,25.0,UUAGAAAGCUGAUGGACCAUAACUG,...,"1,2,3,4,5,6,7,19,20,21,22,23,24,25",88.0,NaN,Hela,100nM,48h,用于抑制CTNNB1靶基因mRNA表达的寡核酸分子及其成套组合物,GUCAAUACCAGGUAGUCGAAAGAUU,100.0,48.0
1,001-01-01-00002-100n-48h-90.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D2,UACAAUAGCAGACACCAUCUGAGGA,25.0,UACAAUAGCAGACACCAUCUGAGGA,...,"1,2,3,4,5,6,7,19,20,21,22,23,24,25",90.0,NaN,Hela,100nM,48h,用于抑制CTNNB1靶基因mRNA表达的寡核酸分子及其成套组合物,AGGAGUCUACCACAGACGAUAACAU,100.0,48.0
2,001-01-01-00003-100n-48h-90.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D3,UGAACAAGACGUUGACUUGGAUCUG,25.0,UGAACAAGACGUUGACUUGGAUCUG,...,"1,2,3,4,5,6,7,19,20,21,22,23,24,25",90.0,NaN,Hela,100nM,48h,用于抑制CTNNB1靶基因mRNA表达的寡核酸分子及其成套组合物,GUCUAGGUUCAGUUGCAGAACAAGU,100.0,48.0
3,001-01-01-00004-100n-48h-89.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D4,UUUAGUUGCAGCAUCUGAAAGAUUC,25.0,UUUAGUUGCAGCAUCUGAAAGAUUC,...,"1,2,3,4,5,6,7,19,20,21,22,23,24,25",89.0,NaN,Hela,100nM,48h,用于抑制CTNNB1靶基因mRNA表达的寡核酸分子及其成套组合物,CUUAGAAAGUCUACGACGUUGAUUU,100.0,48.0
4,001-01-01-00005-100n-48h-87.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D5,UUUCGAAUCAAUCCAACAGUAGCCU,25.0,UUUCGAAUCAAUCCAACAGUAGCCU,...,"1,2,3,4,5,6,7,19,20,21,22,23,24,25",87.0,NaN,Hela,100nM,48h,用于抑制CTNNB1靶基因mRNA表达的寡核酸分子及其成套组合物,UCCGAUGACAACCUAACUAAGCUUU,100.0,48.0

In [3]:
chem_data = ChemistryEncoder(df_clean.copy())

In [4]:
chem_data.update_dataframe()

print(f"Acid Matrix Shape:   {chem_data.file['Sense_Acid_One_Hot'].iloc[0].shape}")
print(f"Sugar Matrix Shape:  {chem_data.file['Sense_Sugar_One_Hot'].iloc[0].shape}")
print(f"Linker Matrix Shape: {chem_data.file['Sense_Linker_One_Hot'].iloc[0].shape}")
print(f"Acid Matrix Shape:   {chem_data.file['Antisense_Acid_One_Hot'].iloc[0].shape}")
print(f"Sugar Matrix Shape:  {chem_data.file['Antisense_Sugar_One_Hot'].iloc[0].shape}")
print(f"Linker Matrix Shape: {chem_data.file['Antisense_Linker_One_Hot'].iloc[0].shape}")

Acid Matrix Shape:   (25, 5)
Sugar Matrix Shape:  (25, 8)
Linker Matrix Shape: (25, 5)
Acid Matrix Shape:   (25, 5)
Sugar Matrix Shape:  (25, 8)
Linker Matrix Shape: (25, 5)

In [5]:
encoded_df = chem_data.file
encoded_df.head()

,ID,patent_ID,Authorization_status,Accession_number,Target_Gene,Gene_ID,The_name_of_double_helix,Antisense_seqence,length_anti_sense_strand,Modifications_AntiSense_strand,...,Title,Modifications_AntiSense_strand_3_5,Concentration_nM,Time_of_administration_h,Sense_Acid_One_Hot,Sense_Sugar_One_Hot,Sense_Linker_One_Hot,Antisense_Acid_One_Hot,Antisense_Sugar_One_Hot,Antisense_Linker_One_Hot
0,001-01-01-00001-100n-48h-88.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D1,UUAGAAAGCUGAUGGACCAUAACUG,25.0,UUAGAAAGCUGAUGGACCAUAACUG,...,用于抑制CTNNB1靶基因mRNA表达的寡核酸分子及其成套组合物,GUCAAUACCAGGUAGUCGAAAGAUU,100.0,48.0,"[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0...."
1,001-01-01-00002-100n-48h-90.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D2,UACAAUAGCAGACACCAUCUGAGGA,25.0,UACAAUAGCAGACACCAUCUGAGGA,...,用于抑制CTNNB1靶基因mRNA表达的寡核酸分子及其成套组合物,AGGAGUCUACCACAGACGAUAACAU,100.0,48.0,"[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0...."
2,001-01-01-00003-100n-48h-90.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D3,UGAACAAGACGUUGACUUGGAUCUG,25.0,UGAACAAGACGUUGACUUGGAUCUG,...,用于抑制CTNNB1靶基因mRNA表达的寡核酸分子及其成套组合物,GUCUAGGUUCAGUUGCAGAACAAGU,100.0,48.0,"[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0...."
3,001-01-01-00004-100n-48h-89.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D4,UUUAGUUGCAGCAUCUGAAAGAUUC,25.0,UUUAGUUGCAGCAUCUGAAAGAUUC,...,用于抑制CTNNB1靶基因mRNA表达的寡核酸分子及其成套组合物,CUUAGAAAGUCUACGACGUUGAUUU,100.0,48.0,"[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0...."
4,001-01-01-00005-100n-48h-87.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D5,UUUCGAAUCAAUCCAACAGUAGCCU,25.0,UUUCGAAUCAAUCCAACAGUAGCCU,...,用于抑制CTNNB1靶基因mRNA表达的寡核酸分子及其成套组合物,UCCGAUGACAACCUAACUAAGCUUU,100.0,48.0,"[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0...."

In [6]:
seq_data = SequenceEncoder(encoded_df.copy())

seq_data.check_nonstandard_bases("Sense_seqence")
seq_data.check_nonstandard_bases("Antisense_seqence")

UGGCAGCUCCUUAUUGUIAUACG
UGGCAGCUCCUUAUUGUIAUACG
ccgccgccuggcCCUGGAGAA
CGUGAAUGGAGAGUICAGCCU
UAAUGUAUUCUAUCUCUcUUU
ACAUUUUGGUCICUAUACUAC
UcUcUccUGAUUAUUUAUCAC
GGUUUUCUUuAAGAUAUUUA
GCCAAGAUGGUCUCGAUuUA
GGAGUCUCACUCUUUCGCuA
CCAAGAUGGUCUCGAUuUuA
CCUCCCGGGUUCACGCuAUA
GCUGGGACUACAGGCGuuuA
CCUGAGUAGCUGGGACUAuA
GGGUUUCACCAUGUUAGUuA
GCUCCACCUCCCGGGUUuAA
CCUGACCUCGUGAUCCAuuA
GGUUUCACCAUGUUAGuuAA
GGAGUGCAGUGGUAUGAUuA
CCCGGGUUCACGCCAUUuUA
GGUUUUCUUuAAGAUAUUUA
GCCAAGAUGGUCUCGAUuUA
GGAGUCUCACUCUUUCGCuA
CCUCCCGGGUUCACGCuAUA
GCUGGGACUACAGGCGuuuA
CCUGAGUAGCUGGGACUAuA
GGGUUUCACCAUGUUAGUuA
GCUCCACCUCCCGGGUUuAA
CCUGACCUCGUGAUCCAuuA
GGUUUCACCAUGUUAGuuAA
GGAGUGCAGUGGUAUGAUuA
CCCGGGUUCACGCCAUUuUA
uguccucucuguugccuuu
uguccucucuguugccuuu
Guccucucuguugccuuuu
Guccucucuguugccuuuu
CUCUAGACCXGUUUUGCUU
CUCUAGACCXGUUUUGCUU
UUCUAGACCXGUUUUGCUA
UUCUAGACCXGUUUUGCUA
[Sense_seqence] nonstandard bases: ['I', 'X', 'c', 'g', 'u']
AIGUAGAAAGGCAUGAAGCAGUU
AUGIAGAAAGGCAUGAAGCAGUU
AUGUIGAAAGGCAUGAAGCAGUU
AUGUAIAAAGGCAUGAAGCAGUU
AUGUAGAIAGGCAUGAAGCAGUU
AIGUAGAAAGGCAUGAAGCAGUU
AUGIAGAAAGGCAUGAAGCAGUU
AUGUAGIAAGGCAUGAAGCAGUU
AUGUAGAIAGGCAUGAAGCAGUU
AIUGUAGAAAGGCAUGAAGCAUU
ACIGUAGAAAGGCAUGAAGCAUU
ACUGIAGAAAGGCAUGAAGCAUU
ACUGUIGAAAGGCAUGAAGCAUU
ACUGUAIAAAGGCAUGAAGCAUU
ACIGUAGAAAGGCAUGAAGCAUU
ACUGIAGAAAGGCAUGAAGCAUU
ACUGUIGAAAGGCAUGAAGCAUU
AUIUAGAAAGGCAUGAAGCAGUU
ACUIUAGAAAGGCAUGAAGCAUU
ACUGUAGIAAGGCAUGAAGCAUU
ACUGUAGIAAGGCAUGAAGCAUU
AUGUAGIAAGGCAUGAAGCAGUU
AUGIAGAAAGGCAUGAAGCAGUU
ACUGIAGAAAGGCAUGAAGCAUU
AUGUIGAAAGGCAUGAAGCAGUU
ACUGUIGAAAGGCAUGAAGCAUU
AUGUAIAAAGGCAUGAAGCAGUU
ACUGUAIAAAGGCAUGAAGCAUU
AUGUAGIAAGGCAUGAAGCAGUU
AUGUAGAIAGGCAUGAAGCAGUU
AUIUAGAAAGGCAUGAAGCAGUU
AUGUAGIAAGGCAUGAAGCAGUU
ACUGUAGIAAGGCAUGAAGCAUU
ACUGUAGIAAGGCAUGAAGCAUU
ACUIUAGAAAGGCAUGAAGCAUU
AUGUIGAAAGGCAUGAAGCAGUU
AUGUIGAAAGGCAUGAAGCAGUU
AUGUIGAAAGGCAUGAAGCAGUU
AUGUAGIAAGGCAUGAAGCAGUU
AUGUIGAAAGGCAUGAAGCAGUU
AUGUAGIAAGGCAUGAAGCAGUU
AUGUIGAAAGGCAUGAAGCAGUU
ACUGIAGAAAGGCAUGAAGCAUU
ACUGUIGAAAGGCAUGAAGCAUU
AUGIAGAAAGGCAUGAAGCAGUU
ACUGIAGAAAGGCAUGAAGCAUU
AUGUIGAAAGGCAUGAAGCAGUU
ACUGUIGAAAGGCAUGAAGCAUU
AUGUAIAAAGGCAUGAAGCAGUU
ACUGUAIAAAGGCAUGAAGCAUU
AUGUAGIAAGGCAUGAAGCAGUU
AUGUAGAIAGGCAUGAAGCAGUU
AUIUAGAAAGGCAUGAAGCAGUU
AUGUAGIAAGGCAUGAAGCAGUU
ACUGUAGIAAGGCAUGAAGCAUU
ACUGUAGIAAGGCAUGAAGCAUU
ACUIUAGAAAGGCAUGAAGCAUU
AUGUIGAAAGGCAUGAAGCAGUU
AUGUAGIAAGGCAUGAAGCAGUU
AUGUIGAAAGGCAUGAAGCAGUU
UUGCACUGCUUGCGGCCCCGcuu
UCGUCAUCAUCGGcuucuucuuc
ACCAGCAGAGCACCCcUCCCCAC
UuAUACCACUGCACUCCAGCCU
UuUACUCAGGAGGCUGAGGCAG
UuAUACCACUGCACUCCAGCCU
ACCCUGCCcUcGAUUUCCC
ACCCUGCCcUcGAUUUCCC
ACACUUGCUGGCCUGUcUG
ACACUUGCUGGCCUGUcUG
AcugccuggcucAcuccuc
AcugccuggcucAcuccuc
GUGUUCCccUuccCAGCcU
GUGUUCCccUuccCAGCcU
ACAUUCUCGAAGUCGGUGACCdTdT
GCCUUUUUACAGCCAACUUdTdT
UGUGCUAGCAACACCCAAAdTdT
ACAUUCUCGAAGUCGGUGACCdTdT
GCCUUUUUACAGCCAACUUdTdT
UGUGCUAGCAACACCCAAAdTdT
ACAUUCUCGAAGUCGGUGACCdTdT
GCCUUUUUACAGCCAACUUdTdT
UGUGCUAGCAACACCCAAAdTdT
[Antisense_seqence] nonstandard bases: ['I', 'c', 'd', 'g', 'u']

{'I', 'c', 'd', 'g', 'u'}

In [7]:
seq_data.update_dataframe()

print(f"Sense Sequence Matrix Shape:      {seq_data.file['Sense_Sequence_One_Hot'].iloc[0].shape}")
print(f"Antisense Sequence Matrix Shape:  {seq_data.file['Antisense_Sequence_One_Hot'].iloc[0].shape}")

Sense Sequence Matrix Shape:      (25, 5)
Antisense Sequence Matrix Shape:  (25, 5)

In [8]:
encoded_df = seq_data.file
encoded_df.head()

,ID,patent_ID,Authorization_status,Accession_number,Target_Gene,Gene_ID,The_name_of_double_helix,Antisense_seqence,length_anti_sense_strand,Modifications_AntiSense_strand,...,Concentration_nM,Time_of_administration_h,Sense_Acid_One_Hot,Sense_Sugar_One_Hot,Sense_Linker_One_Hot,Antisense_Acid_One_Hot,Antisense_Sugar_One_Hot,Antisense_Linker_One_Hot,Sense_Sequence_One_Hot,Antisense_Sequence_One_Hot
0,001-01-01-00001-100n-48h-88.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D1,UUAGAAAGCUGAUGGACCAUAACUG,25.0,UUAGAAAGCUGAUGGACCAUAACUG,...,100.0,48.0,"[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0...."
1,001-01-01-00002-100n-48h-90.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D2,UACAAUAGCAGACACCAUCUGAGGA,25.0,UACAAUAGCAGACACCAUCUGAGGA,...,100.0,48.0,"[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1....","[[0.0, 1.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0...."
2,001-01-01-00003-100n-48h-90.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D3,UGAACAAGACGUUGACUUGGAUCUG,25.0,UGAACAAGACGUUGACUUGGAUCUG,...,100.0,48.0,"[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0...."
3,001-01-01-00004-100n-48h-89.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D4,UUUAGUUGCAGCAUCUGAAAGAUUC,25.0,UUUAGUUGCAGCAUCUGAAAGAUUC,...,100.0,48.0,"[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 0.0, 1.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0...."
4,001-01-01-00005-100n-48h-87.00,CN107365771B,Unknown Status,NM_001330729.2,CTNNB1,1499.0,D5,UUUCGAAUCAAUCCAACAGUAGCCU,25.0,UUUCGAAUCAAUCCAACAGUAGCCU,...,100.0,48.0,"[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1....","[[1.0, 0.0, 0.0, 0.0, 0.0], [1.0, 0.0, 0.0, 0....","[[1.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0....","[[0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0...."